### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by milmazz** [mrtommyb/PyKE#3]
According to this [page](http://keplerscience.arc.nasa.gov/software.html#pyke):

> The current version of PyKE is 2.6.2. PyKE contributors are Martin Still and Tom Barclay. PyKE is an open source project. Contributions of new tasks or enhanced functionality of existing tasks by the community are welcome.

But, this repository is missing a license. Without a license, all code has copyright by the author and may not be used by anyone else :(

Thanks in advance,

**Comment by mrtommyb** [comment]
License can be found via the link in the readme. License is a NASA Open Source License.

**Comment by milmazz** [comment]
@mrtommyb Thanks!
